/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ForensicGuard Design System Colors
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#1f1f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'on-surface': '#e4e2e4',
        'on-surface-variant': '#c0c6d6',
        'inverse-surface': '#e4e2e4',
        'inverse-on-surface': '#303032',
        outline: '#8b91a0',
        'outline-variant': '#414754',
        'surface-tint': '#aac7ff',
        primary: '#aac7ff',
        'on-primary': '#003064',
        'primary-container': '#3e90ff',
        'on-primary-container': '#002957',
        'inverse-primary': '#005db8',
        secondary: '#c2c1ff',
        'on-secondary': '#1800a7',
        'secondary-container': '#3630bf',
        'on-secondary-container': '#b1b1ff',
        tertiary: '#e9b3ff',
        'on-tertiary': '#510074',
        'tertiary-container': '#c863fb',
        'on-tertiary-container': '#460066',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed': '#001b3e',
        'on-primary-fixed-variant': '#00468d',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c2c1ff',
        'on-secondary-fixed': '#0c006b',
        'on-secondary-fixed-variant': '#332dbc',
        'tertiary-fixed': '#f6d9ff',
        'tertiary-fixed-dim': '#e9b3ff',
        'on-tertiary-fixed': '#310048',
        'on-tertiary-fixed-variant': '#7200a3',
        background: '#131315',
        'on-background': '#e4e2e4',
        'surface-variant': '#353437',
        // Legacy color names for compatibility
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        danger: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-md': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'margin': '24px',
      },
      animation: {
        'blob': 'blob 7s infinite',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'shake': 'shake 0.5s ease-in-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-op': 'pulseOp 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        blob: {
          '0%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
          '33%': {
            transform: 'translate(30px, -50px) scale(1.1)',
          },
          '66%': {
            transform: 'translate(-20px, 20px) scale(0.9)',
          },
          '100%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        pulseOp: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      boxShadow: {
        'glow-active': 'inset 0 0 8px rgba(170, 199, 255, 0.2)',
        'glow-primary': '0 0 12px rgba(170, 199, 255, 0.3)',
        'glow-focus': '0 0 8px rgba(170, 199, 255, 0.2)',
      },
      },
    },
  },
  plugins: [],
}
